// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("../theme/Theme.bs.js");
var React = require("react");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Css = require("@emotion/css");

function Button(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  var theme = Theme.useTheme(undefined);
  var style = Css.css({
        width: "59px",
        height: "59px",
        margin: "12px 8px",
        fontSize: theme.fontSize.large,
        backgroundColor: theme.pallete.grey,
        border: "solid 1px #dedede",
        borderRadius: "4px"
      });
  var tmp = {
    className: style
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("button", tmp, children);
}

var make = Button;

exports.make = make;
/* Theme Not a pure module */
