// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var React = require("react");
var Button = require("./Button.bs.js");
var Css = require("@emotion/css");

function ButtonPanel(Props) {
  var container = Css.css({
        width: "auto",
        height: "65%",
        display: "grid",
        gridTemplateColumns: "auto auto auto auto",
        border: "solid 1px #f7f7f7",
        borderRadius: "4px"
      });
  var match = Utils.useCalculator(undefined);
  var setState = match[1];
  return React.createElement("div", {
              className: container
            }, React.createElement(Button.make, {
                  children: "AC",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "AC";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "<=",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "clear";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "%",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "Percentage";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "÷",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "DIV";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "7",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "7";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "8",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "8";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "9",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "9";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "×",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "MUL";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "4",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "4";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "5",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "5";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "6",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "6";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "-",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "SUB";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "1",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "1";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "2",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "2";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "3",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "3";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "+",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "ADD";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "e",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "EXP";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "0",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "0";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: ".",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "DEC";
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "=",
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return "EXE";
                                  }));
                    })
                }));
}

var make = ButtonPanel;

exports.make = make;
/* Utils Not a pure module */
