// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var React = require("react");
var Button = require("./Button.bs.js");
var Css = require("@emotion/css");

function ButtonPanel(Props) {
  var container = Css.css({
        width: "auto",
        height: "65%",
        display: "grid",
        gridTemplateColumns: "auto auto auto auto",
        border: "solid 1px #f7f7f7",
        borderRadius: "4px"
      });
  var match = Utils.useCalculator(undefined);
  var dispatch = match[1];
  return React.createElement("div", {
              className: container
            }, React.createElement(Button.make, {
                  children: "AC",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CLEAR */0);
                    })
                }), React.createElement(Button.make, {
                  children: "<=",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* BACKSPACE */1);
                    })
                }), React.createElement(Button.make, {
                  children: "%",
                  onClick: (function (param) {
                      var value = "%";
                      console.log(value);
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: value
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "÷",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "/"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "7",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "7"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "8",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "8"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "9",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "9"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "×",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "*"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "4",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "4"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "5",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "5"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "6",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "6"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "-",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "-"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "1",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "1"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "2",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "2"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "3",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "3"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "+",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "+"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "e",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "E"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "0",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "0"
                                });
                    })
                }), React.createElement(Button.make, {
                  children: ".",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* CONCAT */{
                                  _0: "."
                                });
                    })
                }), React.createElement(Button.make, {
                  children: "=",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* EVAL */2);
                    })
                }));
}

var make = ButtonPanel;

exports.make = make;
/* Utils Not a pure module */
