// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ButtonPanel = require("./ButtonPanel.bs.js");
var Css = require("@emotion/css");
var DisplayPanel = require("./DisplayPanel.bs.js");

function Calculator(Props) {
  var container = Css.css({
        width: "30vh",
        height: "60vh",
        minWidth: "300px",
        minHeight: "640px",
        border: "solid 1px #dedede",
        borderRadius: "4px"
      });
  return React.createElement("div", {
              className: container
            }, React.createElement(DisplayPanel.make, {}), React.createElement(ButtonPanel.make, {}));
}

var make = Calculator;

exports.make = make;
/* react Not a pure module */
