// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Css = require("@emotion/css");

function DisplayPanel(Props) {
  var container = Css.css({
        width: "100%",
        height: "35%",
        backgroundColor: "salmon"
      });
  return React.createElement("div", {
              className: container
            }, React.createElement("div", undefined, ""));
}

var make = DisplayPanel;

exports.make = make;
/* react Not a pure module */
