// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./Utils.bs.js");
var React = require("react");
var Css = require("@emotion/css");

function DisplayPanel(Props) {
  var container = Css.css({
        width: "100%",
        height: "35%",
        backgroundColor: "salmon"
      });
  var match = Utils.useCalculator(undefined);
  return React.createElement("div", {
              className: container
            }, React.createElement("div", undefined, match[0]));
}

var make = DisplayPanel;

exports.make = make;
/* Utils Not a pure module */
