// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function initialValue_1(f) {
  
}

var initialValue = [
  "",
  initialValue_1
];

var context = React.createContext(initialValue);

var provider = context.Provider;

function Utils$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: Utils$Provider
};

function useCalculator(param) {
  return React.useContext(context);
}

exports.initialValue = initialValue;
exports.context = context;
exports.Provider = Provider;
exports.useCalculator = useCalculator;
/* context Not a pure module */
