// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Button(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  var className = Props.className;
  return React.createElement("button", {
              className: className,
              onClick: onClick
            }, children);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
