// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Theme = require("../theme/Theme.bs.js");
var React = require("react");
var Css = require("@emotion/css");

function Hello(Props) {
  var theme = Theme.useTheme(undefined);
  var hello = Css.css({
        color: theme.pallete.primary,
        backgroundColor: theme.pallete.grey,
        padding: Curry._1(theme.spacing, 2),
        fontSize: theme.fontSize.large,
        borderRadius: "4px"
      });
  return React.createElement("h1", {
              className: hello
            }, "Hello World");
}

var make = Hello;

exports.make = make;
/* Theme Not a pure module */
