// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Count = require("./components/Count.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Button = require("./components/Button.bs.js");
var Css = require("@emotion/css");

var container = Css.css({
      width: "100vw",
      height: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column"
    });

var buttonStyle = Css.css({
      height: "100px",
      fontSize: "30px",
      padding: "10px 30px",
      margin: "20px"
    });

var buttonGroup = Css.css({
      padding: "20px"
    });

function reducer(state, action) {
  if (typeof action !== "number") {
    return {
            count: state.count + action._0 | 0
          };
  }
  switch (action) {
    case /* Inc */0 :
        return {
                count: state.count + 1 | 0
              };
    case /* Dec */1 :
        return {
                count: state.count - 1 | 0
              };
    case /* Double */2 :
        return {
                count: (state.count << 1)
              };
    
  }
}

function App(Props) {
  var match = React.useReducer(reducer, {
        count: 0
      });
  var dispatch = match[1];
  return React.createElement("div", {
              className: container
            }, React.createElement(Count.make, {
                  count: match[0].count
                }), React.createElement("div", {
                  className: buttonGroup
                }, React.createElement(Button.make, {
                      children: "INC",
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* Inc */0);
                        }),
                      className: buttonStyle
                    }), React.createElement(Button.make, {
                      children: "DEC",
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* Dec */1);
                        }),
                      className: buttonStyle
                    }), React.createElement(Button.make, {
                      children: "INC by 3",
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* IncByNumber */{
                                      _0: 3
                                    });
                        }),
                      className: buttonStyle
                    }), React.createElement(Button.make, {
                      children: "Double",
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* Double */2);
                        }),
                      className: buttonStyle
                    }), React.createElement(Button.make, {
                      children: "Async INC",
                      onClick: (function (param) {
                          setTimeout((function (param) {
                                  return Curry._1(dispatch, /* Inc */0);
                                }), 1000);
                          
                        }),
                      className: buttonStyle
                    })));
}

var make = App;

exports.container = container;
exports.buttonStyle = buttonStyle;
exports.buttonGroup = buttonGroup;
exports.reducer = reducer;
exports.make = make;
/* container Not a pure module */
