// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("./theme/Theme.bs.js");
var React = require("react");
var Calculator = require("./components/Calculator.bs.js");
var Css = require("@emotion/css");

var container = Css.css({
      width: "100vw",
      height: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center"
    });

function App(Props) {
  return React.createElement(Theme.Provider.make, {
              value: Theme.initialValue,
              children: React.createElement("div", {
                    className: container
                  }, React.createElement(Calculator.make, {}))
            });
}

var make = App;

exports.container = container;
exports.make = make;
/* container Not a pure module */
