// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Count = require("./components/Count.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Button = require("./components/Button.bs.js");
var Css = require("@emotion/css");

var container = Css.css({
      width: "100vw",
      height: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column"
    });

var buttonStyle = Css.css({
      width: "100px",
      height: "100px",
      fontSize: "50px",
      margin: "20px"
    });

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var count = match[0];
  var onClick = function (e) {
    return Curry._1(setCount, (function (param) {
                  return count + 1 | 0;
                }));
  };
  return React.createElement("div", {
              className: container
            }, React.createElement(Count.make, {
                  count: count
                }), React.createElement(Button.make, {
                  children: "+",
                  onClick: onClick,
                  className: buttonStyle
                }));
}

var make = App;

exports.container = container;
exports.buttonStyle = buttonStyle;
exports.make = make;
/* container Not a pure module */
