// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Css = require("@emotion/css");

var container = Css.css({
      width: "100vw",
      height: "100vh",
      display: "flex",
      justifyContent: "center",
      alignItems: "center"
    });

var hello = Css.css({
      color: "#fff",
      backgroundColor: "hotpink",
      padding: "24px",
      fontSize: "24px",
      borderRadius: "4px"
    });

function App(Props) {
  return React.createElement("div", {
              className: container
            }, React.createElement("h1", {
                  className: hello
                }, "Hello World"));
}

var make = App;

exports.container = container;
exports.hello = hello;
exports.make = make;
/* container Not a pure module */
